spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor_info?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root


  #JPA Settings
    jpa.hibernate.ddl_auto: create/update
  jpa:
    defer-datasource-initialization=true: